CC=gcc
FLAGS=-Wall -Wextra -std=c99 #-Werror

#get_tokens.c
GET_TOKENS=get_tokens
SOURCE_GET_TOKENS=$(GET_TOKENS).c
OBG_GET_TOKENS=$(GET_TOKENS).o
TEST_GET_TOKENS=test_$(GET_TOKENS)

#main.c
NAME_MAIN=main
SOURCE_MAIN=$(NAME_MAIN).c
OBG_MAIN=$(NAME_MAIN).o

#input_check.c
INPUT_CHECK=input_check
SOURCE_INPUT_CHECK=$(INPUT_CHECK).c
OBG_INPUT_CHECK=$(INPUT_CHECK).o

#config.c
CONFIG=config
SOURCE_CONFIG=$(CONFIG).c
OBG_CONFIG=$(CONFIG).o

PROG=graph

CLEAN=rm -f
CLEAN_LIST=$(PROG) $(OBG_GET_TOKENS) $(TEST_GET_TOKENS) $(OBG_MAIN) $(OBG_INPUT_CHECK) $(OBG_CONFIG)



all: $(PROG)#$(TEST_GET_TOKENS)

rebuild: clean all

$(PROG):$(OBG_GET_TOKENS) $(OBG_INPUT_CHECK) $(OBG_MAIN) $(OBG_CONFIG)
	$(CC) $(FLAGS) $^ -o $@

$(OBG_MAIN): $(SOURCE_MAIN)
	$(CC) $(FLAGS) -c $^

$(OBG_GET_TOKENS): $(SOURCE_GET_TOKENS)
	$(CC) $(FLAGS) -c $^

$(OBG_INPUT_CHECK): $(SOURCE_INPUT_CHECK)
	$(CC) $(FLAGS) -c $^

$(OBG_CONFIG): $(SOURCE_CONFIG)
	$(CC) $(FLAGS) -c $^



clean:
	$(CLEAN) $(CLEAN_LIST)

run:
	./$(PROG)




#tests
$(TEST_GET_TOKENS): $(SOURCE_GET_TOKENS)
	$(CC) $(FLAGS) -DTEST $^ -o $@
